[build]
  publish = "CCPhoto"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.17.0"  # Remplacez x.y.z par la version de Node.js que vous utilisez localement.

[build.publish]
  directory = "output"  # Répertoire où les fichiers générés seront disponibles après la construction.
